name: Build iOS App (.app file)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0

      - name: Install dependencies
        run: |
          npm ci

      - name: Install CocoaPods
        run: |
          cd ios/App
          pod install

      - name: Build .app for simulator
        run: |
          cd ios/App
          xcodebuild -scheme App \
            -workspace App.xcworkspace \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            CODE_SIGNING_ALLOWED=NO \
            -derivedDataPath build \
            clean build

      - name: Upload .app as artifact
        uses: actions/upload-artifact@v4
        with:
          name: beatmarket
          path: |
            ios/App/build/Build/Products/Debug-iphonesimulator/*.app
        
      #- name: Archive app for IPA
      #  run: |
      #    cd ios/App
      #    xcodebuild -scheme App \
      #      -workspace App.xcworkspace \
      #      -configuration Release \
      #      -sdk iphoneos \
      #      -archivePath build/App.xcarchive \
      #      CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
      #      clean archive

      #- name: Create ExportOptions.plist
      #  run: |
      #    cat <<EOF > ios/App/ExportOptions.plist
      #    <?xml version="1.0" encoding="UTF-8"?>
      #    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
      #     "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      #    <plist version="1.0">
      #    <dict>
      #      <key>method</key>
      #      <string>ad-hoc</string>
      #      <key>signingStyle</key>
      #      <string>manual</string>
      #      <key>stripSwiftSymbols</key>
      #      <true/>
      #      <key>compileBitcode</key>
      #      <false/>
      #      <key>destination</key>
      #      <string>export</string>
      #      <key>signingCertificate</key>
      #      <string></string>
      #    </dict>
      #    </plist>
      #    EOF

      #- name: Export IPA
      #  run: |
      #    cd ios/App
      #    xcodebuild -exportArchive \
      #      -archivePath build/App.xcarchive \
      #      -exportPath build/export \
      #      -exportOptionsPlist ExportOptions.plist \
      #      CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      #- name: Upload .ipa as artifact
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: beatmarket-ipa
      #    path: |
      #      ios/App/build/export/*.ipa